config/routes.rb
Overmind::Application.routes.draw do
  devise_for :users do
    get "/login", :to => "sso_sessions#show"
    match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]
  end
  resource :sso_session
  get "/login", :to => "sso_sessions#show"
  match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]

  get "/formulario_ics", to: "ics#show", school_id: "current"
  get "/analytics", to: "rankings#history"

  resource :ics, only: [] do
    collection do
      get :select_school
    end
  end
  resources :reports, only: [] do
    collection do
      get 'global_teachers', to: 'reports#global_teachers'
    end
  end
  resources :schools do
    resources :teachers, only: [:show]
    resource :ics, only: [:show, :update]
    resources :reports, only: [] do
      collection do
        get 'pedagogic/:year/:month', to: 'reports#pedagogic_snapshot', as: :pdg
        get 'marketing/:year/:month', to: 'reports#marketing_snapshot', as: :mkt
        get ':return_to/:year/:month/refresh', to: 'reports#refresh', as: :refresh
      end
    end
    resources :monthly_stats, except: [:show] do
      member do
        get 'sync'
      end
      collection do
        get 'sync_create'
      end
    end
    member do
      get 'sync_year'
    end
    collection do
      get "/pa/:account_name", to: 'schools#show_by_name'
      get "/pa/:account_name/ics", to: 'ics#show'
      get "/nid/:nid", to: 'schools#show_by_nucleo_id'
      get "/nid/:nucleo_id/ics", to: 'ics#show'
    end
    resources :sync_requests, only: [:create, :update]
    resource :teacher_ranking, only: [:show, :update]
  end
  resource :ranking, only: [:show, :update] do
    member do
      get 'students'
      get 'history'
    end
  end
  resource :teacher_ranking, only: [:show, :update]
  resources :federations
  resources :users
  resources :monthly_stats, only: [] do
    collection do
      get 'global'
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resources :monthly_stats
      resources :sync_requests, only: [] do
        collection do
          post :pause_all
        end
      end
    end
  end

 root to: 'rankings#show'
 get 'message_door', to: 'message_door#catch'
 get 'sns', to: 'message_door#sns'
 get "/ping", to: "ping#ping"

end

app/models/federation.rb
class Federation < ActiveRecord::Base
  #attr_accessible :name, :nucleo_id
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :users
  has_many :schools

  has_many :school_monthly_stats, through: :schools

  include FederationApi

end

app/controllers/federations_controller.rb
class FederationsController < ApplicationController
  include ApplicationHelper
  before_filter :load_federation, only: [:create]
  load_and_authorize_resource

  def index
    @dropouts_sums = {}
    @dropouts_rates = {}
    @schools_sums = {}
    @students_sums = {}
    @teachers_sums = {}

    @ref_since = 1.year.ago.end_of_month.to_date
    @ref_until = Date.today.end_of_month.to_date

    @federations.each do |federation|
      @schools_sums[federation.id] = federation.schools.enabled_on_nucleo.count

      @teachers_sums[federation.id] = SchoolMonthlyStat.where(name: :team_teachers)
                                                      .joins(:school).where(schools: { federation_id: federation.id })
                                                      .where(ref_date: @ref_until)
                                                      .sum(:value)

      @students_sums[federation.id] = SchoolMonthlyStat.where(name: :students)
                                                      .joins(:school).where(schools: { federation_id: federation.id })
                                                      .where(ref_date: @ref_until)
                                                      .sum(:value)

      @dropouts_sums[federation.id] = SchoolMonthlyStat.where(name: :dropouts)
                                                        .where(school_id: federation.schools.map(&:id))
                                                        .where("ref_date >= ? and ref_date <= ?", @ref_since, @ref_until )
                                                        .sum(:value)
      int_value = LocalStat.new.calculate_dropout_rate(
        dropouts: @dropouts_sums[federation.id],
        students: SchoolMonthlyStat.where(name: :students)
                                    .where(school_id: federation.schools.map(&:id))
                                    .where("ref_date >= ? and ref_date <= ?", @ref_since, @ref_until )
                                    .sum(:value)
      )
      if int_value
        @dropouts_rates[federation.id] = int_value / 100.0
      end
    end

    render layout: role_layout
  end

  def show
    @years = (2010..Date.today.year)
    @year = params[:year] || Date.today.year
    @monthly_stats = Matrixer.new(@federation.school_monthly_stats.for_year(@year)).to_matrix
    respond_to do |format|
      format.html do
        render layout: role_layout
      end
      format.csv do
        response.headers['Content-Disposition'] = "attachment; filename='#{@federation.name}_#{@year}.csv'"
        render 'show.csv.erb'
      end
    end
  end

  def new

  end

  def create
    if @federation.save
      redirect_to federations_path, notice: t('federations.create.success')
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @federation.update_attributes(federation_params)
      redirect_to federations_path, notice: t('federations.update.success')
    else
      render :edit
    end
  end

  def destroy
    @federation.destroy
    redirect_to federations_path, notice: t('federations.destroy.success')
  end

  private

  def federation_params
    params.require(:federation).permit(:name, :nucleo_id)
  end

  def load_federation
    @federation = Federation.new(federation_params)
  end
end

app/views/federations/_form.html.erb
<%= form_for @federation, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                federations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/federations/edit.html.erb
<%- model_class = @federation.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/federations/index.html.erb
<%- model_class = Federation.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table id="federations_table" class="table table-striped tablesorter-blue table-sorter">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= t('.schools_count') %></th>
      <th><%= t('.students_count') %></th>
      <th><%= t('.dropout_rate_last_12_months') %></th>
      <th><%= t('.teachers') %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @federations.each do |federation| %>
      <tr>
        <td><%= link_to_if can?(:read,federation), federation.name, federation %></td>
        <td><%= link_to(@schools_sums[federation.id], ranking_path(federation_id: federation.id)) %></td>
        <td><%= link_to(@students_sums[federation.id], history_ranking_path(ranking: {
          federation_ids: [federation.id],
          column_names: :students,
          ref_since: @ref_since,
          ref_until: @ref_until
        })) %></td>
        <td><%= link_to(@dropouts_rates[federation.id], history_ranking_path(ranking: {
          federation_ids: [federation.id],
          column_names: :dropout_rate,
          ref_since: @ref_since,
          ref_until: @ref_until
        })) if @dropouts_rates[federation.id] %></td>
        <td><%= link_to(@teachers_sums[federation.id], history_ranking_path(ranking: {
          federation_ids: [federation.id],
          column_names: :team_teachers,
          ref_since: @ref_since,
          ref_until: @ref_until
        })) %></td>
        <td>
          <%= link_to(t(".see_all_federation_ics"), federation) if can?(:read,federation) %>
          <%= link_to(t('edit', :default => t("helpers.links.edit")),
                      edit_federation_path(federation), :class => 'btn btn-mini') if can?(:edit,federation) %>
          <%= link_to(t('destroy', :default => t("helpers.links.destroy")),
                      federation_path(federation),
                      :method => :delete,
                      :confirm => t('confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger') if can?(:destroy, federation) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to(t('.new', :default => t("helpers.links.new")),
            new_federation_path,
            :class => 'btn btn-primary') if can?(:create,Federation) %>

app/views/federations/new.html.erb
<%- model_class = @federation.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/federations/show.csv.erb
<% require 'csv' %>
<%= CSV.generate do |csv|
  csv << [nil]+(1...13).map{|m| Date::MONTHNAMES[m]}
  MonthlyStat::VALID_NAMES.each do |name|
    csv << [t("monthly_stat.names.#{name}")] + (1...13).map do |month|
      monthly_stat = @monthly_stats[name][month]
      monthly_stat.try :value
    end
  end
end -%>

app/views/federations/show.html.erb
<%- content_for :title do -%>
  <%= @federation.name %>
<%- end -%>
<%- content_for :breadcrum do -%>
  <%= @federation.name %>
<%- end -%>


<%- model_class = @federation.class -%>
<div class="page-header">
  <%= link_to "<span class='glyphicon glyphicon-cloud-download'></span> #{t('download')}".html_safe, federation_url(id: @federation.id, format: 'csv', year: @year), class: 'btn btn-default', id: 'download-link' %>
  <h1>
    <%= @federation.name %>
  </h1>
</div>

<div id="chartContainer" class="chart-container"></div>

<div id="teachersChartContainer" class="chart-container"></div>

<%= render 'monthly_stats/chrono_table', monthly_stats: @monthly_stats %>

<div>
  <%= link_to t('.schools'), ranking_path(federation_id: @federation.id), class: 'btn btn-primary' %>
</div>

<script>
  chartData = [
    <%- (1...12).each do |month| -%>
    {
      month: "<%= Date::MONTHNAMES[month] %>",
      students: <%= monthly_stat = @monthly_stats[:students][month]; monthly_stat.try(:value) || 0 %>,
      dropouts: <%= monthly_stat = @monthly_stats[:dropouts][month]; monthly_stat.try(:value) || 0 %>,
      enrollments: <%= monthly_stat = @monthly_stats[:enrollments][month]; monthly_stat.try(:value) || 0 %>,
      p_interviews: <%= monthly_stat = @monthly_stats[:p_interviews][month]; monthly_stat.try(:value) || 0 %>,
      assistant_students: <%= monthly_stat = @monthly_stats[:assistant_students][month]; monthly_stat.try(:value) || 0 %>,
      professor_students: <%= monthly_stat = @monthly_stats[:professor_students][month]; monthly_stat.try(:value) || 0 %>,
      master_students: <%= monthly_stat = @monthly_stats[:master_students][month]; monthly_stat.try(:value) || 0 %>,
      male_students: <%= monthly_stat = @monthly_stats[:male_students][month]; monthly_stat.try(:value) || 0 %>,
      female_students: <%= monthly_stat = @monthly_stats[:female_students][month]; monthly_stat.try(:value) || 0 %>
    },
    <%- end -%>
    <%- month = 12 -%>
    {
      month: "<%= Date::MONTHNAMES[month] %>",
      students: <%= monthly_stat = @monthly_stats[:students][month]; monthly_stat.try(:value) || 0 %>,
      dropouts: <%= monthly_stat = @monthly_stats[:dropouts][month]; monthly_stat.try(:value) || 0 %>,
      enrollments: <%= monthly_stat = @monthly_stats[:enrollments][month]; monthly_stat.try(:value) || 0 %>,
      p_interviews: <%= monthly_stat = @monthly_stats[:p_interviews][month]; monthly_stat.try(:value) || 0 %>,
      assistant_students: <%= monthly_stat = @monthly_stats[:assistant_students][month]; monthly_stat.try(:value) || 0 %>,
      professor_students: <%= monthly_stat = @monthly_stats[:professor_students][month]; monthly_stat.try(:value) || 0 %>,
      master_students: <%= monthly_stat = @monthly_stats[:master_students][month]; monthly_stat.try(:value) || 0 %>,
      male_students: <%= monthly_stat = @monthly_stats[:male_students][month]; monthly_stat.try(:value) || 0 %>,
      female_students: <%= monthly_stat = @monthly_stats[:female_students][month]; monthly_stat.try(:value) || 0 %>
  }
  ]
</script>