config/routes.rb
Overmind::Application.routes.draw do
  devise_for :users do
    get "/login", :to => "sso_sessions#show"
    match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]
  end
  resource :sso_session
  get "/login", :to => "sso_sessions#show"
  match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]

  get "/formulario_ics", to: "ics#show", school_id: "current"
  get "/analytics", to: "rankings#history"

  resource :ics, only: [] do
    collection do
      get :select_school
    end
  end
  resources :reports, only: [] do
    collection do
      get 'global_teachers', to: 'reports#global_teachers'
    end
  end
  resources :schools do
    resources :teachers, only: [:show]
    resource :ics, only: [:show, :update]
    resources :reports, only: [] do
      collection do
        get 'pedagogic/:year/:month', to: 'reports#pedagogic_snapshot', as: :pdg
        get 'marketing/:year/:month', to: 'reports#marketing_snapshot', as: :mkt
        get ':return_to/:year/:month/refresh', to: 'reports#refresh', as: :refresh
      end
    end
    resources :monthly_stats, except: [:show] do
      member do
        get 'sync'
      end
      collection do
        get 'sync_create'
      end
    end
    member do
      get 'sync_year'
    end
    collection do
      get "/pa/:account_name", to: 'schools#show_by_name'
      get "/pa/:account_name/ics", to: 'ics#show'
      get "/nid/:nid", to: 'schools#show_by_nucleo_id'
      get "/nid/:nucleo_id/ics", to: 'ics#show'
    end
    resources :sync_requests, only: [:create, :update]
    resource :teacher_ranking, only: [:show, :update]
  end
  resource :ranking, only: [:show, :update] do
    member do
      get 'students'
      get 'history'
    end
  end
  resource :teacher_ranking, only: [:show, :update]
  resources :federations
  resources :users
  resources :monthly_stats, only: [] do
    collection do
      get 'global'
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resources :monthly_stats
      resources :sync_requests, only: [] do
        collection do
          post :pause_all
        end
      end
    end
  end

 root to: 'rankings#show'
 get 'message_door', to: 'message_door#catch'
 get 'sns', to: 'message_door#sns'
 get "/ping", to: "ping#ping"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  #attr_accessible :full_name, :username

  has_and_belongs_to_many :schools, join_table: 'schools_teachers'

  has_many :monthly_stats, dependent: :destroy

  validates_uniqueness_of :username, allow_nil: true, allow_blank: true

  # Will find or create teacher from padma_username and full_name.
  #
  # Some updating will be applied to teacher to avoid duplication.
  # If school not linked, will be linked.
  # If full_name given but missing in record, will be updated
  # If username given but missing in record, will be updated
  #
  # @param padma_username [String]
  # @param full_name [String]
  # @param school [School]
  # @return [Teacher]
  def self.smart_find(padma_username,full_name,school=nil)
    t = nil
    unless padma_username.blank?
      t = Teacher.find_by_username(padma_username)
    end
    if t
      if t.full_name.blank? && !full_name.blank?
        t.update_attribute(:full_name, full_name)
      end
    else
      t = Teacher.find_by_full_name(full_name)
      if t && t.username.blank? && !padma_username.blank?
        t.update_attribute(:username, padma_username)
      end
    end
    unless t
      t = Teacher.create!(username: padma_username, full_name: full_name)
    end

    if school
      unless t.schools.include?(school)
        t.schools << school
        t.save
      end
    end

    t
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  load_and_authorize_resource except: :show

  def show
    @school = School.find(params[:school_id])
    authorize! :read, @school
    @teacher = Teacher.find params[:id]

    @years = (2010..Date.today.year)
    @year = params[:year] || Date.today.year

    current_school_teachers = @school.account.present?? @school.account.users.map(&:username) : nil
    @teachers = current_school_teachers.blank?? @school.teachers : @school.teachers.select{|t| t.username.in?(current_school_teachers) }

    stats_scope = @school.teacher_monthly_stats.for_year(@year).where(teacher_id: params[:id])
    @stats = Matrixer.new(stats_scope).to_matrix

    @stat_names = get_stat_names.map(&:to_sym)

    queue_stats_resyncs

    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Disposition'] = "attachment; filename='teacher_#{@teacher.id}_#{@year}.csv'"
        render 'show.csv.erb'
      end
    end
  end

  private

  def queue_stats_resyncs
    if ENV["queue_sync_on_teacher_show"] == "true"
      @stats.each do |stat_name, by_month|
        by_month.each do |month_number, values|
          next if month_number==:total
          ref_date = Date.civil(@year.to_i, month_number.to_i, 1).end_of_month
          service = MonthlyStat.service_for(@school, stat_name, ref_date)
          if service == "crm"
            unless Delayed::Job.where("handler like '%School\n  raw_attributes:\n    id:%#{@school.id}%fetch_stat_from_crm%#{stat_name}%#{ref_date.to_s}%by_teacher%'").exists?
              @school.delay.fetch_stat_from_crm(stat_name, ref_date, async: true, by_teacher: true)
            end
          end
        end
      end
    end
  end

  def get_stat_names
    regular = if params[:ranking] && params[:ranking][:column_names]
      cookies[:anual_report_stats] = params[:ranking][:column_names].reject(&:blank?)
    else
      # default
      if cookies[:anual_report_stats]
        cookies[:anual_report_stats].split("&")
      else
        %W(students dropouts dropout_rate demand conversion_rate p_interviews enrollments enrollment_rate )
      end
    end
    regular + MonthlyStat::MANUAL_STATS
  end
end

app/views/teachers/show.html.erb
<%- content_for :title do -%>
  <%= @teacher.full_name %>
<%- end -%>
<%- breadcrum "#{@teacher.full_name} #{@year}" -%>

<div class='schools-container'>
  <header class='schools-head'>
    <p><%= @year %></p>
    <nav class='schools-navbar' role='navigation'>
      <div class='filter-controls'>
        <div class='btn-group'>
          <%= link_to school_teacher_url(school_id: @school.id, teacher_id: @teacher.id, year: @year.to_i - 1), class: 'btn btn-secondary btn-sm' do %>
            <span class='glyphicon glyphicon-chevron-left'></span>
          <% end %>
          <% unless @year.to_i == Time.zone.now.year %>
            <%= link_to school_teacher_url(school_id: @school.id, teacher_id: @teacher.id, year: @year.to_i + 1), class: 'btn btn-secondary btn-sm' do %>
              <span class='glyphicon glyphicon-chevron-right'></span>
            <% end %>
          <% end %>
        </div>
        <%= render :partial => 'schools/sync_request_notification' %>
      </div>
      <div class='filter-controls filter-controls-right'>
        <%# link_to "<span class='glyphicon glyphicon-download'></span>".html_safe, school_url(id: @school.id, format: 'csv', year: @year), class: 'btn btn-secondary btn-sm', id: 'download-link' %>
      </div>
    </nav>
  </header>
  <section class='schools-content'>
    <div id="newChartContainer" class="chart-container"></div> <!-- chart -->
    <ul class='nav nav-tabs' role='tablist'>
      <li>
        <%= link_to @school.full_name, school_path(id: @school.id, year: @year) %>
      </li>
      <%- @teachers.each do |teacher| %>
        <li <%= "class='active'".html_safe if @teacher.id == teacher.id%>>
          <%= link_to teacher.try(:full_name), school_teacher_path(@school,teacher.id) %>
        </li>
      <%- end %>
    </ul>
    <div class='tab-content tab-content-border'>
      <div id='<%= @teacher.id %>' class='tab-pane active'>
        <% unless @stats.values.reject(&:empty?).empty? -%>
          <%= render "monthly_stats/chrono_table", monthly_stats: @stats, teacher_stats: true, title: @teacher.try(:full_name) %>
        <% end -%>
      </div>
    </div>
  </section>
</div>

<div class="page-header" hidden>
  <%= link_to "<span class='glyphicon glyphicon-download'></span>".html_safe, school_url(id: @school.id, format: 'csv', year: @year), class: 'btn btn-secondary btn-sm', id: 'download-link' %>
  <h2>
    <div>
      <span id="current_year" title="<%= t('schools.show.click_to_change') %>"><%= @year %></span>
      <%= form_tag nil, method: 'GET', class: 'form-inline', id: 'set-year'  do -%>
        <%= select_tag( :year, options_for_select(@years,@year)) %>
        <%= submit_tag(t('see'), class: 'btn') %>
      <%- end -%>
    </div>
  </h2>
  <%= render :partial => 'schools/sync_request_notification' %>
</div>

<%= content_for :body_end do %>
  <% 
  @graph_stat_names = @stat_names.select do |sn|
    !sn.in?(MonthlyStat::MANUAL_STATS.map(&:to_sym)) && sn != :students_average_age
  end
  %>
<script>
    var chartData = <%= (1..12).map do |month|
      r = { month: Date::MONTHNAMES[month] }
      @rendering_pers = false
      @graph_stat_names.each do |name|
        val = (@stats[name.to_sym][month].try(:value) || 0)
        if MonthlyStat.is_a_rate?(name)
          @rendering_pers = true
          val = val.to_f/100
        end
        r.merge!({ name => val })
      end
      r
    end.to_json.html_safe -%>;

    chart = new AmCharts.AmSerialChart();
    chart.dataProvider = chartData;
    chart.categoryField = "month";

    chart.color = "#AAAAAA";
    chart.startDuration = 2;
    chart.autoMargins = false;
    chart.marginTop = 30;
    chart.marginBottom = 30;
    chart.marginLeft = 80;
    chart.marginRight = 80;

    valAxis = new AmCharts.ValueAxis();
    valAxis.position = "left";
    valAxis.axisColor = "#2d66bb";
    valAxis.gridAlpha = 0;
    valAxis.fillColor = "#2d66bb";
    valAxis.fillAlpha = 0.1;
    valAxis.dashLength = 3;
    chart.addValueAxis(valAxis);

    <% if @rendering_pers %>
      perAxis = new AmCharts.ValueAxis();
      perAxis.minimum = 0;
      perAxis.maximum = 100;
      perAxis.position = "right";
      perAxis.gridAlpha = 0;
      perAxis.dashLength = 3;
      chart.addValueAxis(perAxis);
    <% end %>

    <% @graph_stat_names.each do |stat_name| %>
      <%= stat_name %>_graph = new AmCharts.AmGraph();
      <%= stat_name %>_graph.valueField = "<%= stat_name %>";
      <%= stat_name %>_graph.title = $("#stats-names").data("<%= stat_name %>");
      <%= stat_name %>_graph.type = "line";
      <%= stat_name %>_graph.lineThickness = <%= MonthlyStat.is_a_rate?(stat_name)? '1' : '2' %>;
      <%= stat_name %>_graph.bullet = "<%= MonthlyStat.is_a_rate?(stat_name)? 'none' : 'round' %>";
      <%= stat_name %>_graph.dashLength = <%= MonthlyStat.is_a_rate?(stat_name)? '3' : '1' %>;
      <%= stat_name %>_graph.valueAxis = <%= MonthlyStat.is_a_rate?(stat_name)? "perAxis" : "valAxis" %>;
      <%= case stat_name
          when :students
            "students_graph.lineColor = 'black';"
          when :male_students
            "male_students_graph.lineColor = 'blue';"
          when :female_students
            "female_students_graph.lineColor = 'pink';"
          when :enrollments
            "enrollments_graph.lineColor = 'green';"
          when :enrollment_rate
            "enrollment_rate_graph.lineColor = '#3fff3f';"
          when :dropouts
            "dropouts_graph.lineColor = 'red';"
          when :dropout_rate
            "dropout_rate_graph.lineColor = '#ff3f3f';"
          else
            ""
          end.html_safe
      %>
      chart.addGraph(<%= stat_name %>_graph);
    <% end %>
    
    chartCursor = new AmCharts.ChartCursor();
    chart.addChartCursor( chartCursor );

    legend = new AmCharts.AmLegend();
    legend.align = "center";
    legend.markerType = "circle";
    chart.addLegend(legend);

    chart.write('newChartContainer');
</script>
<% end %>