config/routes.rb
Overmind::Application.routes.draw do
  devise_for :users do
    get "/login", :to => "sso_sessions#show"
    match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]
  end
  resource :sso_session
  get "/login", :to => "sso_sessions#show"
  match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]

  get "/formulario_ics", to: "ics#show", school_id: "current"
  get "/analytics", to: "rankings#history"

  resource :ics, only: [] do
    collection do
      get :select_school
    end
  end
  resources :reports, only: [] do
    collection do
      get 'global_teachers', to: 'reports#global_teachers'
    end
  end
  resources :schools do
    resources :teachers, only: [:show]
    resource :ics, only: [:show, :update]
    resources :reports, only: [] do
      collection do
        get 'pedagogic/:year/:month', to: 'reports#pedagogic_snapshot', as: :pdg
        get 'marketing/:year/:month', to: 'reports#marketing_snapshot', as: :mkt
        get ':return_to/:year/:month/refresh', to: 'reports#refresh', as: :refresh
      end
    end
    resources :monthly_stats, except: [:show] do
      member do
        get 'sync'
      end
      collection do
        get 'sync_create'
      end
    end
    member do
      get 'sync_year'
    end
    collection do
      get "/pa/:account_name", to: 'schools#show_by_name'
      get "/pa/:account_name/ics", to: 'ics#show'
      get "/nid/:nid", to: 'schools#show_by_nucleo_id'
      get "/nid/:nucleo_id/ics", to: 'ics#show'
    end
    resources :sync_requests, only: [:create, :update]
    resource :teacher_ranking, only: [:show, :update]
  end
  resource :ranking, only: [:show, :update] do
    member do
      get 'students'
      get 'history'
    end
  end
  resource :teacher_ranking, only: [:show, :update]
  resources :federations
  resources :users
  resources :monthly_stats, only: [] do
    collection do
      get 'global'
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resources :monthly_stats
      resources :sync_requests, only: [] do
        collection do
          post :pause_all
        end
      end
    end
  end

 root to: 'rankings#show'
 get 'message_door', to: 'message_door#catch'
 get 'sns', to: 'message_door#sns'
 get "/ping", to: "ping#ping"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  #attr_accessible :full_name, :username

  has_and_belongs_to_many :schools, join_table: 'schools_teachers'

  has_many :monthly_stats, dependent: :destroy

  validates_uniqueness_of :username, allow_nil: true, allow_blank: true

  # Will find or create teacher from padma_username and full_name.
  #
  # Some updating will be applied to teacher to avoid duplication.
  # If school not linked, will be linked.
  # If full_name given but missing in record, will be updated
  # If username given but missing in record, will be updated
  #
  # @param padma_username [String]
  # @param full_name [String]
  # @param school [School]
  # @return [Teacher]
  def self.smart_find(padma_username,full_name,school=nil)
    t = nil
    unless padma_username.blank?
      t = Teacher.find_by_username(padma_username)
    end
    if t
      if t.full_name.blank? && !full_name.blank?
        t.update_attribute(:full_name, full_name)
      end
    else
      t = Teacher.find_by_full_name(full_name)
      if t && t.username.blank? && !padma_username.blank?
        t.update_attribute(:username, padma_username)
      end
    end
    unless t
      t = Teacher.create!(username: padma_username, full_name: full_name)
    end

    if school
      unless t.schools.include?(school)
        t.schools << school
        t.save
      end
    end

    t
  end
end

app/models/teacher_ranking.rb
class TeacherRanking

  extend  ActiveModel::Naming
  extend  ActiveModel::Translation
  include ActiveModel::Validations
  include ActiveModel::Conversion

  DEFAULT_COLUMN_NAMES = [:students, :p_interviews, :enrollments, :enrollment_rate, :dropout_rate] 
  VALID_COLUMNS = MonthlyStat::VALID_NAMES

  COLUMNS_FOR_VIEW = [
   [:students, :enrollments, :dropouts],
   [:enrollment_rate, :dropout_rate],
   [:dropouts_begginers, :dropouts_intermediates, :begginers_dropout_rate, :swasthya_dropout_rate],
   [:male_students, :female_students],
   [:aspirante_students, :sadhaka_students, :yogin_students, :chela_students, :graduado_students, :assistant_students, :professor_students, :master_students],
   [:demand, :interviews, :p_interviews, :emails, :phonecalls, :website_contact, :messaging_comms, :social_comms],
   [:conversion_rate]
  ]

  attr_accessor :school_ids,
                :federation_ids,
                :column_names,
                :ref_since,
                :ref_until,
                :ref_date

  validate :valid_date_period

  def initialize(attributes=nil)
    attributes = {} if attributes.nil?

    set_dates(attributes)
    set_federation_ids(attributes)
    set_school_ids(attributes)
    set_column_names(attributes)
    
  end

  def matrix
    @matrix ||= TeacherRankingMatrix.new(stats).matrix
  end

  def monthly_stats
    scope = TeacherMonthlyStat.select([:name, :value, :teacher_id])
                             .includes(:school)
                             .includes(:teacher)
                             .where(ref_date: (ref_date.to_date.beginning_of_month..ref_date.end_of_month.to_date))
                             .where(name: @column_names)
    scope = scope.where(schools: { federation_id: @federation_ids }) unless @federation_ids.nil?
    scope = scope.where(schools: { id: @school_ids }) unless @school_ids.nil?
    
    scope.all.group_by(&:teacher)
  end

  def stats
    pre_scope = TeacherMonthlyStat.where(ref_date: (ref_since.to_date..ref_until.to_date))
    pre_scope = pre_scope.where(schools: { federation_id: @federation_ids }) unless @federation_ids.nil?
    pre_scope = pre_scope.where(schools: { id: @school_ids }) unless @school_ids.nil?

    scope = pre_scope.select([:name, :value, :teacher_id])
                     .includes(:school)
                     .includes(:teacher)
                     .where(name: @column_names)

    scope.group_by(&:teacher).map do |teacher, stats|
      stats.group_by(&:name).map do |name, stats|
        ReducedStat.new(teacher: teacher,
                        stats: stats,
                        stats_scope: pre_scope.joins(:school).where(teacher_id: teacher.id),
                        name: name,
                        reduce_as: :avg)
      end
    end.flatten
  end

  def teacher_ids
    @teacher_ids ||= stats.map(&:teacher_id)
  end

  def school_stats
    if @school_stats
      @school_stats
    else
      @school_stats = {}
      school_ids.each do |sid|
        @school_stats[sid] = {
          "month" => {},
          "avg" => {}
        }
        values = SchoolMonthlyStat.where(school_id: sid,
                                name: column_names,
                                ref_date: ref_date.end_of_month)
        values.each do |sms|
          @school_stats[sid]["month"][sms.name] = sms
        end

        column_names.each do |name|
          @school_stats[sid]["avg"][name] = ReducedStat.new(
            name: name,
            stats_scope: SchoolMonthlyStat.where(
                                school_id: sid,
                                ref_date: ref_since.to_date..ref_until.to_date),
            reduce_as: :avg
          )
        end
      end
      @school_stats
    end
  end

  def persisted?
    false
  end

  private

  def valid_date_period
    if self.ref_since && self.ref_until <= self.ref_since
      errors.add(:ref_until, t('ranking.validations.ref_until'))
    end
  end

  def set_dates(attributes)
    [:ref_since, :ref_until, :ref_date].each do |ref|
      val = if attributes[ref]
        attributes[ref]
      elsif attributes["#{ref}(1i)"] && attributes["#{ref}(2i)"]
        Date.new(attributes["#{ref}(1i)"].to_i,
                 attributes["#{ref}(2i)"].to_i,
                 1).end_of_month
      end
      self.send("#{ref}=", val)
    end

    # defaults
    self.ref_since = 4.months.ago.end_of_month.to_date if self.ref_since.nil?
    self.ref_until = 1.month.ago.end_of_month.to_date if self.ref_until.nil?
    self.ref_date = Date.today if self.ref_date.nil?
  end

  def set_school_ids(attributes)
    @school_ids = attributes.fetch(:school_ids , School.pluck(:id))
    if @school_ids.first.is_a?(String)
      @school_ids = @school_ids.map(&:to_i)
    end
  end

  def set_federation_ids(attributes)
    @federation_ids = attributes.fetch(:federation_ids , Federation.pluck(:id)).reject(&:blank?)
    if @federation_ids.first.is_a?(String)
      @federation_ids = @federation_ids.map(&:to_i)
    end
  end

  def set_column_names(attributes)
    @column_names = attributes.fetch( :column_names , DEFAULT_COLUMN_NAMES).reject(&:blank?)
    if @column_names.first.is_a?(String)
      @column_names = @column_names.map(&:to_sym)
    end
  end
end

app/controllers/teacher_rankings_controller.rb
class TeacherRankingsController < ApplicationController

  before_filter :load_school

  def show
    authorize! :read, TeacherRanking

    @federation = @school.federation if @school

    unless params[:school_id]
      @federations = Federation.accessible_by(current_ability)
      @schools = School.accessible_by(current_ability)
    end
    
    if params[:teacher_ranking].nil?
      params[:teacher_ranking] = {}
    end

    @teacher_ranking = TeacherRanking.new params[:teacher_ranking].merge({ federation_ids: [@federation.try(:id)],
                                                                           school_ids: [@school.id] })
    
    
    unless SyncRequest.on_ref_date(year: @teacher_ranking.ref_date.year, month: @teacher_ranking.ref_date.month)
                      .where(school_id: @school.id)
                      .where(state: %W(ready running paused))
                      .exists?
      sr = SyncRequest.create(year: @teacher_ranking.ref_date.year, month: @teacher_ranking.ref_date.month, school_id: @school.id, priority: 10)
      sr.queue_dj
    end

    respond_to do |format|
      format.html { render action: :show }
      format.json do
        render json: @matrix
      end
      format.csv do
        response.headers['Content-Disposition'] = "attachment; filename='rankings.csv'"
        render 'show.csv.erb'
      end
    end
  end

  def update
    show
  end

  private

  def load_school
    if School.exists?(params[:school_id])
      @school = School.find(params[:school_id])
    else
      @school = School.where(account_name: params[:school_id]).try :first
    end

    if @school.nil?
      @school = School.find_by_account_name(current_user.account_name)
    end

    if @school.nil?
      raise ActiveRecord::RecordNotFound
    end

    @school
  end

end

app/helpers/teacher_ranking_helper.rb
module TeacherRankingHelper
  def teacher_is_currently_in_team?(teacher)
    usernames = @school.account.users.map(&:username)
    u = PadmaUser.find teacher.try(:username)
    u && u.username.in?(usernames)
  end

  def non_zero_stats?(stats)
    stats && ( stats.sum(&:value) > 0 )
  end

  def any_diff?(acums,teachers_ranking)
    !teachers_ranking.column_names.select do |name|
      !MonthlyStat.is_a_rate?(name) && ((acums[name] || 0) - (teachers_ranking.school_stats[@school.id]["month"][name.to_s].try(:value) || 0) != 0)
    end.empty?
  end
end

app/views/teacher_rankings/_school_total.html.erb
<%= print_value @teacher_ranking.school_stats[@school.id]["month"][name.to_s] %>
<% unless MonthlyStat.is_a_rate?(name) %>
  <% if acum != (@teacher_ranking.school_stats[@school.id]["month"][name.to_s].try(:value) || 0 ) %>
    <% if SyncRequest.where(year: @teacher_ranking.ref_date.year,
                            school_id: @school.id,
                            month: @teacher_ranking.ref_date.month
                           )
                     .where(state: %W(ready running paused))
                     .exists? %>
      <p>
        Error? we're re calculating
      </p>
    <%- elsif can?(:create, SyncRequest) && @school.padma_enabled? -%>
      <p>
        <%= form_for [@school,@school.sync_requests.new(year: @teacher_ranking.ref_date.year, month: @teacher_ranking.ref_date.month, priority: 10)], method: 'POST', id: 'request-sync-form' do |f| %>
          <%= f.hidden_field :year %>
          <%= f.hidden_field :month %>
          <%= f.hidden_field :priority %>
          <input type="hidden" name="return_to" value="<%= url_for params %>" />
          <button type='submit' class='btn btn-link btn-sm'>
            Error? refresh: 
            <span class='glyphicon glyphicon-refresh'></span>
          </button>
        <% end -%>
      </p>
    <%- end -%>
  <% end %>
<% end %>

app/views/teacher_rankings/_sync_request.html.erb
<% unless MonthlyStat.is_a_rate?(name) %>
  <% if acum != (@teacher_ranking.school_stats[@school.id]["month"][name.to_s].try(:value) || 0 ) %>
    <% if SyncRequest.where(year: @teacher_ranking.ref_date.year,
                            school_id: @school.id,
                            month: @teacher_ranking.ref_date.month
                           )
                     .where(state: %W(ready running paused))
                     .exists? %>
      <p>
        Error? we're re calculating
      </p>
    <%- elsif can?(:create, SyncRequest) && @school.padma_enabled? -%>
      <p>
        <%= form_for [@school,@school.sync_requests.new(year: @teacher_ranking.ref_date.year, month: @teacher_ranking.ref_date.month, priority: 10)], method: 'POST', id: 'request-sync-form' do |f| %>
          <%= f.hidden_field :year %>
          <%= f.hidden_field :month %>
          <%= f.hidden_field :priority %>
          <input type="hidden" name="return_to" value="<%= url_for params %>" />
          <button type='submit' class='btn btn-link btn-sm'>
            Error? refresh: 
            <span class='glyphicon glyphicon-refresh'></span>
          </button>
        <% end -%>
      </p>
    <%- end -%>
  <% end %>
<% end %>

app/views/teacher_rankings/show.csv.erb
<% require 'csv' %>

<%= CSV.generate do |csv|
  header = @ranking.column_names.map{|name| t("monthly_stat.names.#{name}")}
  header.unshift(t('ranking.name'))
  csv <<  header
  @ranking.matrix.each do |school, stats_hash|
    line = []
    line << school.name
    @ranking.column_names.each do |name|
      line << (stats_hash[name.to_s].nil? ? nil : stats_hash[name.to_s].value)
    end
    csv << line
  end
end -%>

app/views/teacher_rankings/show.html.erb
<%- breadcrum t("teacher_ranking.title") -%>

<div class='stats-teacher-container'>
  <nav class='statsteacher-navbar' role='navigation'>
    <div class='filter-controls'>
      <% url = @school.present? ? school_teacher_ranking_path(@school) : teacher_ranking_path %>
      <%= form_for @teacher_ranking, url: url, method: :put, :html => { class: 'form-inline' } do |f| %>
        <div class='form-group'>
          <div class='label-block'><%= t('teacher_ranking.date') %></div>
          <%= f.date_select :ref_date, {discard_day: true}, { class: 'form-control' } %>
        </div>
        <div class='form-group form-group-flex'>
          <div class='label-block'><%= t('teacher_ranking.date_range') %></div>
          <%= f.date_select :ref_since, {discard_day: true}, { class: 'form-control' } %>
          <span class='label-to'>a</span>
          <%= f.date_select :ref_until, {discard_day: true}, { class: 'form-control' } %>
        </div>
        <div class="btn-group">
          <%= f.select   :column_names,
                         TeacherRanking::COLUMNS_FOR_VIEW.flatten.map{|name| [t("monthly_stat.names.#{name}"), name]},
                         {},
                         {
                            data: {
                              'none-selected-text' => t('ranking.choose_columns')},
                            multiple: :multiple,
                            class: 'choose-columns-select'
                          }
          %>
        </div>
        <button type="submit" class="btn btn-secondary btn-sm"><%= t('submit') %></button>
      <% end -%>
    </div>
  </nav>
  <section class='statsteacher-content'>
    <div class='table-responsive'>
      <table id="statsteacher-table" class="table table-striped table-condensed tablesorter-blue">
        <thead>
          <tr>
            <th></th>
            <th colspan="<%= @teacher_ranking.column_names.size %>" class='text-center'>
              <%= t("teacher_ranking.monthly_stats_for", :month => l(@teacher_ranking.ref_date, :format => "%B"))  %>
            </th>
            <th colspan="<%= @teacher_ranking.column_names.size %>" class='text-center'>
              <%= t("teacher_ranking.average_stats_for", :start_month => l(@teacher_ranking.ref_since, :format => "%B"), :end_month => l(@teacher_ranking.ref_until, :format => "%B")) %>
            </th>
          </tr>
          <tr>
            <th><%= t('ranking.name') %></th>
            <% @teacher_ranking.column_names.each do |name| %>
              <th><%= t("monthly_stat.names.#{name}") %></th>
            <% end %>
            <% @teacher_ranking.column_names.each do |name| %>
              <th><%= t("monthly_stat.names.#{name}") %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% monthly_stats =  @teacher_ranking.monthly_stats %>
          <% acums_by_name = {} %>
          <% @teacher_ranking.column_names.each{|n| acums_by_name[n] = 0 } %>
          <% @teacher_ranking.matrix.each do |teacher, stats_hash| %>
            <% if teacher %>
              <% teacher_monthly_stats = monthly_stats[teacher] %>
              <% if teacher_is_currently_in_team?(teacher) || non_zero_stats?(teacher_monthly_stats)  %>
                <tr>
                  <th>
                    <%= teacher.try(:full_name) %>
                  </th>
                  <% @teacher_ranking.column_names.each do |name| %>
                    <% monthly_stat = teacher_monthly_stats.detect {|ms| ms.name == name.to_s} unless teacher_monthly_stats.blank? %>
                    <% acums_by_name[name] += monthly_stat.value if monthly_stat %>
                    <td>
                      <span><%= print_value monthly_stat %></span>
                    </td>
                  <% end %>
                  <% @teacher_ranking.column_names.each do |name| %>
                    <% if stats_hash[name.to_s].nil? -%>
                      <td></td>
                    <% else -%>
                      <td>
                        <span data-toggle="tooltip" data-placement="top" title="<%= t('ranking.sample_size', size: stats_hash[name.to_s].size) %>">
                          <%= print_value stats_hash[name.to_s] %>
                        </span>
                      </td>
                    <% end -%>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          <% end %>
          <% if any_diff?(acums_by_name,@teacher_ranking) %>
            <tr>
              <th><span style="display: none" id="lastInAlphabeticalOrder">zz</span><%= t(".teacherless") %></th>
              <% @teacher_ranking.column_names.each do |name| %>
                <td>
                  <% unless MonthlyStat.is_a_rate?(name) %>
                    <%= (@teacher_ranking.school_stats[@school.id]["month"][name.to_s].try(:value) || 0) - (acums_by_name[name] || 0) %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <th><%= t(".school_total") %></th>
            <% @teacher_ranking.column_names.each do |name| %>
              <td>
                <%= print_value @teacher_ranking.school_stats[@school.id]["month"][name.to_s] %>
              </td>
            <% end %>
            <% @teacher_ranking.column_names.each do |name| %>
              <td>
                <%= print_value @teacher_ranking.school_stats[@school.id]["avg"][name] %>
              </td>
            <% end %>
          </tr>
        </tfoot>
      </table>
    </div>
  </section>
</div>

<div id="options-panel" class="panel panel-default" hidden>
  <div class="panel-heading" data-toggle="collapse" data-target="#options-panel .panel-body">
    <%= t('teacher_ranking.options') %>
    <span class="glyphicon glyphicon-collapse-down pull-right"></span>
  </div>
  <div class="panel-body collapse">
    <% url = @school.present? ? school_teacher_ranking_path(@school) : teacher_ranking_path %>
    <%= form_for @teacher_ranking, url: url, method: :put, class: "form-horizontal" do |f| %>
      <h4><%= t('teacher_ranking.date') %></h4>
      <div class="form-group form-inline">
        <%= f.date_select :ref_date, {discard_day: true}, { class: 'form-control' } %>
      </div>
      <h4><%= t('teacher_ranking.date_range') %></h4>
      <div class="form-group form-inline">
        <%= f.date_select :ref_since, {discard_day: true}, { class: 'form-control' } %>
        <%= f.date_select :ref_until, {discard_day: true}, { class: 'form-control' } %>
      </div>


      <% if @federations.present? && @federations.size > 1 %>
        <h4><%= t('ranking.federations') %></h4>
        <div class="btn-group form-group" data-toggle="buttons">
          <% @federations.each do |fed| -%>
            <label class="checkbox-inline col-sm-offset-1 btn btn-default btn-sm">
              <%= f.check_box 'federation_ids', {multiple: true, checked: federation_selected?(fed.id,@teacher_ranking)}, fed.id, false %> <%= fed.name %>
            </label>
          <% end -%>
        </div>
      <% end %>

      <% if @schools.present? && @schools.size > 1 %>
        <h4><%= t('teacher_ranking.schools') %></h4>
        <div class="btn-group form-group" data-toggle="buttons">
          <% @schools.each do |school| -%>
            <label class="checkbox-inline col-sm-offset-1 btn btn-default btn-sm">
            <%= f.check_box 'school_ids', {multiple: true, checked: school_selected?(school.id,@teacher_ranking)}, school.id, false %> <%= school.name %>
          </label>
          <% end -%>
        </div>
      <% end %>

      <h4><%= t('ranking.columns')%></h4>
      <% TeacherRanking::COLUMNS_FOR_VIEW.each do |row_of_names| -%>
        <div class="btn-group input-group" data-toggle="buttons">
          <% row_of_names.each do |name|-%>
            <label class="btn btn-default btn-sm">
              <%= f.check_box :column_names, {multiple: true, checked: column_name_selected?(name,@teacher_ranking)}, name, false %> <%= t("monthly_stat.names.#{name}") %>
            </label>
          <% end -%>
        </div>
      <% end -%>
        <div class="form-group">
          <button type="submit" class="btn btn-primary col-sm-offset-0"><%= t('submit') %></button>
        </div>
    <% end -%>
  </div>
</div>