config/routes.rb
Overmind::Application.routes.draw do
  devise_for :users do
    get "/login", :to => "sso_sessions#show"
    match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]
  end
  resource :sso_session
  get "/login", :to => "sso_sessions#show"
  match '/logout', to: "sso_sessions_#destroy", via: [:get, :delete]

  get "/formulario_ics", to: "ics#show", school_id: "current"
  get "/analytics", to: "rankings#history"

  resource :ics, only: [] do
    collection do
      get :select_school
    end
  end
  resources :reports, only: [] do
    collection do
      get 'global_teachers', to: 'reports#global_teachers'
    end
  end
  resources :schools do
    resources :teachers, only: [:show]
    resource :ics, only: [:show, :update]
    resources :reports, only: [] do
      collection do
        get 'pedagogic/:year/:month', to: 'reports#pedagogic_snapshot', as: :pdg
        get 'marketing/:year/:month', to: 'reports#marketing_snapshot', as: :mkt
        get ':return_to/:year/:month/refresh', to: 'reports#refresh', as: :refresh
      end
    end
    resources :monthly_stats, except: [:show] do
      member do
        get 'sync'
      end
      collection do
        get 'sync_create'
      end
    end
    member do
      get 'sync_year'
    end
    collection do
      get "/pa/:account_name", to: 'schools#show_by_name'
      get "/pa/:account_name/ics", to: 'ics#show'
      get "/nid/:nid", to: 'schools#show_by_nucleo_id'
      get "/nid/:nucleo_id/ics", to: 'ics#show'
    end
    resources :sync_requests, only: [:create, :update]
    resource :teacher_ranking, only: [:show, :update]
  end
  resource :ranking, only: [:show, :update] do
    member do
      get 'students'
      get 'history'
    end
  end
  resource :teacher_ranking, only: [:show, :update]
  resources :federations
  resources :users
  resources :monthly_stats, only: [] do
    collection do
      get 'global'
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resources :monthly_stats
      resources :sync_requests, only: [] do
        collection do
          post :pause_all
        end
      end
    end
  end

 root to: 'rankings#show'
 get 'message_door', to: 'message_door#catch'
 get 'sns', to: 'message_door#sns'
 get "/ping", to: "ping#ping"

end

app/models/monthly_stat/money_stat.rb
# encoding: utf-8
class MonthlyStat
  module MoneyStat

    def needs_unit?
      name.to_s.in?(%W(gross_income expenses profit))
    end

    def suggested_currency
      if @suggested_currency
        @suggested_currency
      else
        if school
          if school.account # padma account   
            @suggested_currency = case school.account.country
            when "Argentina"
              "ARS"
            when "Chile"
              "CLP"
            when "Brazil"
              "BRL"
            when "France", "Finland", "Portugal", "España", "United Kingdom", "Italy"
              "EUR"
            when "United States"
              "USD"
            when "Canada"
              "CAD"
            else
              "BRL"
            end
          end
        end
      end
    end
  end
end

app/controllers/api/v0/monthly_stats_controller.rb
# @restful_api v0
class Api::V0::MonthlyStatsController < Api::V0::ApiController
  
  # @action GET
  # @url /api/v0/monthly_stats
  # @required [String] api_key
  #
  # @optional [Hash] where
  # @key_for where year always use with month
  # @key_for where month always use with year
  # @key_for where name
  # @key_for where account_name
  #         
  #
  def index
    @monthly_stats = MonthlyStat.api_where(where_params).includes(:school).all
    render json: {
        collection: @monthly_stats,
        total: @monthly_stats.size
    }
  end

  # @url /api/v0/monthly_stats/:id
  # @action GET
  # @required [String] api_key
  # @required [Integer] id
  # @response Array<MonthlyStat>
  def show
    @monthly_stat = MonthlyStat.find(params[:id])
    render json: @monthly_stat
  end

  # Creates MonthlyStat. If it already exists, existing stat will be updated.
  #
  # @url /api/v0/monthly_stats
  # @action POST
  #
  # @required [String] api_key
  # @required [Hash] monthly_stat
  # @required [String] monthly_stat[account_name]
  # @required [String] monthly_stat[name] stat name. Valid values are:
  #   :enrollments,
  #   :dropouts,
  #   :students,
  #   :assistant_students, # students at Assistant lev
  #   :professor_students, # students at Professor level.
  #   :master_students, # students at Master level.
  #   :interviews, :p_interviews
  #
  # @example_response
  #   id: 1234 - status: 201
  # @response_field id [Integer] id of created/updated monthly_stat (only for status: 201)
  #
  # @example_response {errors: [], message: 'Stat not saved'} - status: 400
  # @response_field errors [Array] (only for status: 400)
  def create
    
    remove_blank_teacher_username

    if @monthly_stat = find_this_stat(monthly_stat_params)
      @monthly_stat.value = params[:monthly_stat][:value]
      @monthly_stat.service = params[:monthly_stat][:service]
    else
      if is_a_teacher_stat?
        @monthly_stat = TeacherMonthlyStat.new(monthly_stat_params)
      else
        @monthly_stat = MonthlyStat.new(monthly_stat_params)
      end
    end
    if @monthly_stat.save!
      render json: {id: @monthly_stat.id}, status: 201
    else
      render json: {
          errors: @monthly_stat.errors,
          message: "Stat not saved"
      }, status: 400
    end
  end

  # @action PUT
  # @url /api/v0/monthly_stats/:id
  # @required [String] api_key
  # @retuired [Integer] id
  def update
    @monthly_stat = MonthlyStat.find(params[:id])
    if @monthly_stat.update_attributes monthly_stat_params
      render json: 'ok'
    else
      render json: {
          message: 'Stat not saved',
          errors: @monthly_stat.errors
      }, status: 400
    end
  end

  # @url /api/v0/monthly_stats/:id
  # @action DELETE
  # @required [String] api_key
  # @required [Integer] id
  def destroy
    @monthly_stat = MonthlyStat.find(params[:id])
    @monthly_stat.destroy
    render json: 'ok', status: 200
  end

  private

  def remove_blank_teacher_username
    if params[:monthly_stat]
      if params[:monthly_stat][:teacher_username].blank?
        params[:monthly_stat].delete(:teacher_username)
      end
    end
  end

  def is_a_teacher_stat?
    params[:monthly_stat] && !params[:monthly_stat][:teacher_username].blank?
  end

  # Finds MonthlyStat duplicate
  # @param [Hash] attributes
  # @return [MonthlyStat]
  def find_this_stat(attributes)
    school = School.find_by_account_name(attributes[:account_name])
    @teacher = Teacher.smart_find(attributes[:teacher_username],'',school) if attributes[:teacher_username]
    MonthlyStat.where(name: attributes[:name],
                      ref_date: attributes[:ref_date],
                      school_id: school.try(:id),
                      teacher_id: @teacher.try(:id)
                     ).first
  end

  def where_params
    params.require(:where).permit!
  end

  def monthly_stat_params
    params.require(:monthly_stat).permit(
      :value,
      :name,
      :school_id,
      :ref_date,
      :service,
      :account_name,
      :id,
      :teacher_username,
      :unit
    )
  end

end

app/controllers/monthly_stats_controller.rb
class MonthlyStatsController < ApplicationController

  before_filter :load_monthly_stat, only: [:create]
  load_and_authorize_resource :school, except: [:global]
  load_and_authorize_resource through: :school, except: [:global]

  def index; end

  def new; end

  def show
    respond_to do |format|
      format.json { respond_with_bip(@monthly_stat) }
    end
  end

  def create
    respond_to do |format|
      if @monthly_stat.save
        format.html {redirect_to @school, notice: t('monthly_stats.create.success')}
        format.json do
          render json: {id: @monthly_stat.id}
        end
      else
        format.html {render :new}
        format.json do
          render json: @monthly_stat.errors.full_messages, :status => :unprocessable_entity
        end
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @monthly_stat.update_attributes(monthly_stat_params)
        format.html {redirect_to @school, notice: t('monthly_stats.update.success')}
        format.json do
          render json: {id: @monthly_stat.id}
        end
      else
        format.html {render :edit}
        format.json do
          render json: @monthly_stat.errors.full_messages, :status => :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @monthly_stat.destroy
    respond_to do |format|
      format.html {redirect_to @school}
      format.js {render :layout => false}
    end
  end

  def sync
    @monthly_stat.update_from_service!
    redirect_to school_path(id: @school.id, year: params[:year])
  end

  def sync_create
    ref_date = Date.parse(params[:ref_date])
    SchoolMonthlyStat.create_from_service!(@school,params[:name],ref_date.end_of_month)
    redirect_to school_path(id: @school.id, year: ref_date.year)
end

  def global
    authorize! :see_global, MonthlyStat
    @years = 2010..Date.today.year
    @year = params[:year] || Time.zone.today.year
    stats = MonthlyStat.for_year(@year)
    @monthly_stats = Matrixer.new(stats).to_matrix
    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Disposition'] = "attachment; filename='#{@year}_global.csv'"
        render 'global.csv.erb'
      end
    end
  end

  private
  def monthly_stat_params
    params.require(:monthly_stat).permit(
      :value,
      :name,
      :school_id,
      :ref_date,
      :service,
      :account_name,
      :teacher_username,
      :id,
      :unit
    )
  end

  def load_monthly_stat
    @monthly_stat = MonthlyStat.new(monthly_stat_params)
    @monthly_stat.school_id = params[:school_id] if @monthly_stat.school_id.nil?
  end
end

app/helpers/monthly_stats_helper.rb
module MonthlyStatsHelper

  def print_value_with_link(monthly_stat)
    if !monthly_stat.respond_to?(:url_to_crm_list) || monthly_stat.url_to_crm_list.nil? || (monthly_stat.account_name != current_user.padma.current_account_name)
      print_value(monthly_stat)
    else
      link_to print_value(monthly_stat), monthly_stat.url_to_crm_list, target: '_blank'
    end
  end
  
  def print_value(monthly_stat, options = {})
    v = monthly_stat.try :value
    return '' if skip_value(v)

    val = if monthly_stat.is_a_rate?
      # rates are represented as 'cents' in integer.
      sufix = options[:sufix] || "%"
      "#{number_with_precision(v.to_f/100, precision: 2)}#{sufix}"
    elsif monthly_stat.is_a?(ReducedStat) && (monthly_stat.reduce_as.to_sym == :avg)
      number_with_precision(v, precision: 0)
    else
      v
    end

    if monthly_stat.unit.blank?
      val
    else
      "#{val} #{monthly_stat.unit}"
    end
  end

  def can_sync_month?(month)
   can?(:create, SyncRequest) && @school.padma_enabled? && Date.civil(@year.to_i,month.to_i,1).end_of_month <= Time.zone.today.to_date.end_of_month if @school && @year
  end

  def can_sync_update?(stat)
    if stat.is_a?(TeacherMonthlyStat)
      LocalStat.is_local_stat?(stat.name)
    else
      stat.service.present?
    end
  end
  
  # @option options [String] stat_name
  # @return [Boolean]
  def can_sync_create?(options={})
    is_local_stat = LocalStat.is_local_stat?(options[:stat_name])
    not_teacher_stats = !options[:teacher_stats]
    month_past = (options[:ref_date].end_of_month < Date.today)
    is_local_stat && not_teacher_stats && month_past
  end

  # @param options [Hash]
  # @option options [MonthlyStat] monthly_stat
  # @option options [String] stat_name
  # @option options [Date] ref_date
  # @option options [Boolean] teacher_stats
  # @return [Boolean]
  def in_place_create?(options={})
    permitions = current_ability.can?(:create,MonthlyStat)
    month_past = (options[:ref_date].end_of_month < Date.today)
    not_teacher_stats = !options[:teacher_stats]
    is_not_local_stat   = !LocalStat.is_local_stat?(options[:stat_name])

    permitions && month_past && not_teacher_stats && is_not_local_stat
  end

  # @param options [Hash]
  # @option options [MonthlyStat] monthly_stat
  # @option options [Date] ref_date
  # @option options [Boolean] teacher_stats
  # @return [Boolean]
  def in_place_edit?(options={})
    permitions = current_ability.can?(:update,MonthlyStat)
    service_blank = options[:monthly_stat].service.blank?
    month_past = (options[:ref_date].end_of_month < Date.today)
    is_not_reduced_stat = !options[:monthly_stat].is_a?(ReducedStat)
    is_not_local_stat   = !LocalStat.is_local_stat?(options[:monthly_stat].name)
    not_teacher_stats = !options[:teacher_stats]

    permitions && service_blank && month_past && is_not_reduced_stat && not_teacher_stats && is_not_local_stat
  end

  def can_delete?(options={})
    permitions = current_ability.can?(:destroy,MonthlyStat)
    service_blank = options[:monthly_stat].service.blank?
    month_past = (options[:ref_date].end_of_month < Date.today)
    is_not_reduced_stat = !options[:monthly_stat].is_a?(ReducedStat)
    is_not_local_stat   = !LocalStat.is_local_stat?(options[:monthly_stat].name)
    not_teacher_stats = !options[:teacher_stats]

    permitions && month_past && is_not_reduced_stat && not_teacher_stats && is_not_local_stat
  end

  def skip_value(value)
    value.nil? || ((value.is_a?(Float) || value.is_a?(BigDecimal)) && value.nan?)
  end

end

app/views/monthly_stats/_chrono_table.html.erb
<%- model_class = MonthlyStat.new.class -%>
<%
begin
  teacher_stats
rescue NameError
  teacher_stats = false
end
-%>

<% title ||= t('.title', :default => model_class.model_name.human.pluralize)%>
<div class='table-responsive'>
  <table id='statstable' class="table table-striped table-condensed">
    <thead>
      <tr>
        <th></th>
        <%- (1..12).each do |m| -%>
          <th class="toggle-views">
            <%= Date::MONTHNAMES[m] %>
            <%- if can_sync_month?(m)  -%>
              <%= link_to('<span class="glyphicon glyphicon-refresh"></span>'.html_safe,
                          school_sync_requests_path(school_id: @school.id,
                                                    sync_request: {
                                                      priority: 15,
                                                      year: @year,
                                                      month: m}),
                          method: 'POST',
                          rel: 'tooltip',
                          data: {'original-title' => t('monthly_stats.chrono_table.sync_month')},
                          :class => 'red') %>
            <% end -%>
          </th>
        <%- end -%>
        <th><%= t('.anual') %></th>
      </tr>
    </thead>
    <tbody>
    <% tabindex=0 %>
    <% if @stat_names.nil?
         @stat_names = MonthlyStat::VALID_NAMES
       end %>
    <% @stat_names.reject{|n|n.to_s.in?(%W(conversion_rate
                                           gross_income
                                           expenses
                                           profit
                                           team_teachers
                                       ))
        }.each do |name| -%>
      <% next if teacher_stats && (monthly_stats[name].empty? && MonthlyStat.is_manual?(name)) -%>
      <tr>
        <th>
          <%= t("monthly_stat.names.#{name}") %>
          <% if monthly_stat_description(name) -%>
            <span class='glyphicon glyphicon-question-sign pull-right' data-toggle='popover' data-placement='left' data-content='<%= monthly_stat_description(name) %>' data-trigger='hover' tabindex='-1'></span>
          <% end -%>
        </th>
        <%- (1..12).each do |month| -%>
          <% ref_date = Date.civil(@year.to_i,month,1) -%>
          <% tabindex = tabindex + 1 %>
          <td class="toggle-views">
            <% monthly_stat = monthly_stats[name][month] -%>
            <% if @school.nil? -%>
              <%= print_value(monthly_stat) %>
            <% else -%>
              <% if monthly_stat.nil? %>
                <% if in_place_create?(ref_date: ref_date, stat_name: name, teacher_stats: teacher_stats) -%>
                  <%# TODO para esto precisamos el fork best_in_place_post que hizo alex %>
                  <%# best_in_place monthly_stat,
                                  :value,
                                  :nil => "<span class='glyphicon glyphicon-pencil'></span>".html_safe,
                                  :classes => "editable",
                                  :object_name => "monthly_stat",
                                  :type => :input,
                                  :path => "/schools/#{@school.id}/monthly_stats",
                                  :post => 'true',
                                  :data => {name: name,
                                            toggle: "tooltip",
                                            "original-title" => t('edit'),
                                            placement: "top",
                                            refdate: "#{ref_date}",
                                            service: ""
                                  },
                                  :tabindex => tabindex %>
                <% elsif can_sync_create?(ref_date: ref_date, stat_name: name, teacher_stats: teacher_stats) -%>
                  <%= link_to('<span class="glyphicon glyphicon-refresh"></span>'.html_safe,
                              sync_create_school_monthly_stats_path(name: name, school_id: @school.id, ref_date: ref_date),
                              rel: 'tooltip',
                              data: {'original-title' => "calculate"},
                              :class => 'red') %>
                <% end -%>
            <% else %>
              <% if in_place_edit?(monthly_stat: monthly_stat, ref_date: ref_date, teacher_stats: teacher_stats) -%>
                <%= best_in_place monthly_stat,
                                  :value,
                                  :type => :input,
                                  :object_name => "monthly_stat",
                                  :path => "/schools/#{@school.id}/monthly_stats/#{monthly_stat.id}",
                                  :data => {
                                              toggle: "tooltip",
                                              "original-title" => t('edit'),
                                              placement: "top"
                                    },
                                  :tabindex => tabindex
                %>
              <% else -%>
                <%= print_value_with_link monthly_stat %>
              <% end -%>
            <% end %>
            <%- unless monthly_stat.nil? || monthly_stat.is_a?(ReducedStat) || @school.nil? -%>
              <span class="show-on-hover"><% if in_place_edit?(monthly_stat: monthly_stat, ref_date: ref_date, teacher_stats: teacher_stats) %>
                  <a href="#" data-toggle="tooltip" data-original-title="<%= t('edit')%>" class="editable">
                    <span class='glyphicon glyphicon-pencil'></span>
                  </a>
                <% end %>
                <% if can_delete?(monthly_stat: monthly_stat, ref_date: ref_date, teacher_stats: teacher_stats) %>
                  <%= link_to('<span class="glyphicon glyphicon-trash"></span>'.html_safe,
                              school_monthly_stat_path(id: monthly_stat, school_id: @school.id),
                              rel: 'tooltip',
                              data: {
                                'original-title' => t('delete'),
                                'toggle' => 'tooltip',
                                :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))
                                },
                              :method => :delete,
                              :remote => true,
                              :id => "monthly-stat-#{monthly_stat.id}",
                              :class => 'red deletable') %>
                <% end %>
                <%- if can_sync_update?(monthly_stat) -%>
                  <%= link_to('<span class="glyphicon glyphicon-refresh"></span>'.html_safe,
                              sync_school_monthly_stat_path(id: monthly_stat, school_id: @school.id, year: @year),
                              rel: 'tooltip',
                              data: {'original-title' => "sync from #{monthly_stat.service}"},
                              :class => 'red') %>
                <%- end -%></span>
            <%- end -%>
          <% end -%>
          </td>
        <%- end -%>
        <td class="subtotal">
          <% if false # deshabilito hasta decidir mejor forma de evitar confusion con el story #161357381 %>
            <% if teacher_stats %>
              <%= print_value(monthly_stats[name][:total]) %>
            <% else %>
              <%= print_year_subtotal_with_link( reduced_stat: monthly_stats[name][:total], year: @year )  %>
            <% end %>
          <% else %>
            <%= print_value(monthly_stats[name][:total]) %>
          <% end %>
        </td>
      </tr>
    <%- end -%>
    <% unless monthly_stats[:swasthya_students_subtotal] == {} %>
      <tr>
        <th><%= t('monthly_stat.names.swasthya_students_subtotal') %></th>
        <%- (1..12).each do |month| -%>
          <td><%= monthly_stats[:swasthya_students_subtotal][month].try(:value) %></td>
        <%- end -%>
      </tr>
    <%- end -%>

    <% unless monthly_stats[:conversion_rate] == {} %>
      <tr>
        <th>
          <%= t('monthly_stat.names.conversion_rate') %>
          <%- if !monthly_stats[:conversion_rate].select{|_,stat|stat.is_a?(ReducedStat)}.empty?  -%>
            <span class='glyphicon glyphicon-question-sign pull-right' data-toggle='popover' data-original-title='<%= t('monthly_stats.chrono_table.conversion_calculation') %>' data-content='<%= t('monthly_stats.chrono_table.conversion_explanation') %>' data-trigger='focus' tabindex='-1'></span>
          <%- end -%>
        </th>
        <%- (1...13).each do |month| -%>
          <td>
            <% monthly_stat = monthly_stats[:conversion_rate][month] -%>
            <%= print_value monthly_stat %>
          </td>
        <%- end -%>
      </tr>
    <%-	end %>

    </tbody>
  </table>
</div>

app/views/monthly_stats/_form.html.erb
<%= form_for @monthly_stat, :url => school_monthly_stat_url, html: {:class => 'form-horizontal'} do |f| %>

  <div class="alert alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h2><%= t('warning') %></h2>
    <%= t('.manual_edition_disable_sync') %>
  </div>
  <%= f.hidden_field :service, value: '' %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :name, MonthlyStat::VALID_NAMES %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :ref_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :ref_date, class: 'date_select', discard_day: true, end_year: Date.today.year %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :value, :class => 'number_field' %>
    </div>
  </div>

  <%#
  <div class="control-group">
    %= f.label :school_id, :class => 'control-label' %
    <div class="controls">
      %= f.number_field :school_id, :class => 'number_field' %
    </div>
  </div>
  %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                @school, :class => 'btn' %>
  </div>
<% end %>

app/views/monthly_stats/_list.html.erb
<%- model_class = MonthlyStat.new.class -%>
<h2><%=t '.title', :default => model_class.model_name.human.pluralize %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ref_date) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @monthly_stats.each do |monthly_stat| %>
      <tr>
        <td><%= monthly_stat.id %></td>
        <td><%= monthly_stat.ref_date %></td>
        <td><%= monthly_stat.name %></td>
        <td><%= monthly_stat.value %></td>
        <td><%=l monthly_stat.created_at %></td>
        <td>
          <%= link_to(t('.edit', :default => t("helpers.links.edit")),
                      edit_school_monthly_stat_path(monthly_stat), :class => 'btn btn-mini') if can?(:edit,monthly_stat) %>
          <%= link_to(t('.destroy', :default => t("helpers.links.destroy")),
                      school_monthly_stat_path(monthly_stat),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger') if can?(:destroy,monthly_stat) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to(t('.new', :default => t("helpers.links.new")),
            new_school_monthly_stat_path(school_id: @school.id),
            :class => 'btn btn-primary') if can?(:create,@school.monthly_stats.new) %>

app/views/monthly_stats/global.html.erb
<%- content_for :title do -%>
  Global
<%- end -%>

<div class="page-header">
  <%= link_to "<span class='glyphicon glyphicon-cloud-download'></span> #{t('download')}".html_safe, global_monthly_stats_url(format: 'csv', year: @year), class: 'btn btn-default', id: 'download-link' %>
  <h1>
    <span id="current_year" title="<%= t('schools.show.click_to_change') %>"><%= @year %></span>
    <%= form_tag nil, method: 'GET', class: 'form-inline', id: 'set-year', style: 'display: none'  do -%>
      <%= select_tag( :year, options_for_select(@years,@year)) %>
      <%= submit_tag(t('see'), class: 'btn') %>
    <%- end -%>
  </h1>
</div>

<div id="chartContainer" class="chart-container"></div>
<div id="teachersChartContainer" class="chart-container"></div>


<%= render 'monthly_stats/chrono_table', monthly_stats: @monthly_stats %>

<script>
  chartData = [
    <%- (1...12).each do |month| -%>
    {
      month: "<%= Date::MONTHNAMES[month] %>",
      students: <%= monthly_stat = @monthly_stats[:students][month]; monthly_stat.try(:value) || 0 %>,
      dropouts: <%= monthly_stat = @monthly_stats[:dropouts][month]; monthly_stat.try(:value) || 0 %>,
      enrollments: <%= monthly_stat = @monthly_stats[:enrollments][month]; monthly_stat.try(:value) || 0 %>,
      p_interviews: <%= monthly_stat = @monthly_stats[:p_interviews][month]; monthly_stat.try(:value) || 0 %>,
      assistant_students: <%= monthly_stat = @monthly_stats[:assistant_students][month]; monthly_stat.try(:value) || 0 %>,
      professor_students: <%= monthly_stat = @monthly_stats[:professor_students][month]; monthly_stat.try(:value) || 0 %>,
      master_students: <%= monthly_stat = @monthly_stats[:master_students][month]; monthly_stat.try(:value) || 0 %>,
      male_students: <%= monthly_stat = @monthly_stats[:male_students][month]; monthly_stat.try(:value) || 0 %>,
      female_students: <%= monthly_stat = @monthly_stats[:female_students][month]; monthly_stat.try(:value) || 0 %>
    },
    <%- end -%>
    <%- month = 12 -%>
    {
      month: "<%= Date::MONTHNAMES[month] %>",
      students: <%= monthly_stat = @monthly_stats[:students][month]; monthly_stat.try(:value) || 0 %>,
      dropouts: <%= monthly_stat = @monthly_stats[:dropouts][month]; monthly_stat.try(:value) || 0 %>,
      enrollments: <%= monthly_stat = @monthly_stats[:enrollments][month]; monthly_stat.try(:value) || 0 %>,
      p_interviews: <%= monthly_stat = @monthly_stats[:p_interviews][month]; monthly_stat.try(:value) || 0 %>,
      assistant_students: <%= monthly_stat = @monthly_stats[:assistant_students][month]; monthly_stat.try(:value) || 0 %>,
      professor_students: <%= monthly_stat = @monthly_stats[:professor_students][month]; monthly_stat.try(:value) || 0 %>,
      master_students: <%= monthly_stat = @monthly_stats[:master_students][month]; monthly_stat.try(:value) || 0 %>,
      male_students: <%= monthly_stat = @monthly_stats[:male_students][month]; monthly_stat.try(:value) || 0 %>,
      female_students: <%= monthly_stat = @monthly_stats[:female_students][month]; monthly_stat.try(:value) || 0 %>
    }
  ]
</script>